#!/bin/bash

cat > /app/ctrl.conf <<EOF
{
	"Control-agent": {
		"http-host": "$KEA_CA_HOST",
		"http-port": $KEA_CA_PORT,

		"control-sockets": {
			"dhcp4": {},
			"d2": {}
		},

		"trust-anchor": "$KEA_TLS_CA",
		"cert-file": "$KEA_TLS_CERT",
		"key-file": "$KEA_TLS_KEY"
	}
}
EOF

/usr/bin/stork-agent
