#!/bin/bash

cat > /app/ctrl.conf <<EOF
{
	"Control-agent": {
		"http-host": "$KEA_CA_HOST",
		"http-port": $KEA_CA_PORT,

		"control-sockets": {
			"dhcp4": {},
			"d2": {}
		}
	}
}
EOF

/usr/bin/stork-agent
